export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Heading',
  headline: 'Some text about the service',
  description: 'some other text telling you about the product.',
  buttonLabel: 'Home',
  imgStart: false,
  alt: 'Car',
  img: require('../../images/svg-1.svg'),
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Heading',
  headline: 'Some text about the service',
  description: 'some other text telling you about the product.',
  buttonLabel: 'Next Button',
  imgStart: true,
  alt: 'Tree',
  img: require('../../images/svg-2.svg'),
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Heading',
  headline: 'Some text about the service',
  description: 'some other text telling you about the product.',
  buttonLabel: 'Another Button',
  imgStart: false,
  alt: 'Paper',
  img: require('../../images/svg-3.svg'),
  dark: false,
  primary: false,
  darkText: true,
};
